CREATE TABLE user(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, date TIMESTAMP NOT NULL);

CREATE TABLE category(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, user_id INTEGER NOT NULL, title VARCHAR(255) NOT NULL,date TIMESTAMP NOT NULL);

CREATE TABLE channel(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,category_id INTEGER NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255), link VARCHAR(255) NOT NULL,lastSynchronize TIMESTAMP NOT NULL,synchronize BOOLEAN NOT NULL);
CREATE TABLE feed(id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,channel_id INTEGER NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255), pubDate TIMESTAMP NOT NULL,link VARCHAR(255) NOT NULL, visualized BOOLEAN NOT NULL);

insert into category values(null, "Default", now());